version: '3'

services:
  php-api:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  php-api-doc:
    image: swaggerapi/swagger-ui
    ports:
      - "8181:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml